spring:
  profiles:
    active: h2

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  batch:
    job:
      names: ${job.name:NONE}

logging:
  level:
    org.springframework.batch: DEBUG

---
spring:
  config:
    activate:
      on-profile: h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/spring_batch
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      names: ${job.name:NONE}

logging:
  level:
    org.springframework.batch: DEBUG
